# Generated by Django 3.0.2 on 2020-01-14 09:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('content', ckeditor.fields.RichTextField()),
                ('tile_image', models.ImageField(upload_to='blog_tile')),
                ('author_name', models.CharField(max_length=45)),
                ('catchy_line', models.CharField(max_length=400)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blogs.Blog')),
                ('user', models.ManyToManyField(blank=True, related_name='all_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_time'],
            },
        ),
    ]
