# Generated by Django 3.0.2 on 2020-01-09 05:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('content', ckeditor.fields.RichTextField()),
                ('tile_image', models.ImageField(upload_to='blog_tile')),
                ('author_name', models.CharField(max_length=45)),
                ('catchy_line', models.CharField(max_length=400)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
