# Generated by Django 3.0.2 on 2020-01-10 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_auto_20200110_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
