# Generated by Django 3.0.2 on 2020-01-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='card_images')),
                ('hashtag', models.CharField(max_length=264)),
            ],
        ),
    ]
